output_root: "outputs"
output_version: "baseline"
backup_name: "weights"
log_name: "logs"

#labels: ["aeroplane", "bicycle", "bird", "boat", "bottle", "bus", "car", "cat", "chair", "cow", "diningtable", "dog", "horse", "motorbike", "person", "pottedplant", "sheep", "sofa", "train", "tvmonitor"]
labels: ["17"]
#labels: ["face"]

#data_root_dir: "/media/lishundong/DATA2/docker/data/VOC_face/onedet_cache"
data_root_dir: "/media/lishundong/DATA2/docker/data/VOC_key/onedet_cache"
#data_root_dir: "/media/lishundong/DATA2/docker/data/VOCdevkit/onedet_cache"
#data_root_dir: "/Users/ming/Desktop/tmp/VOCdevkit/onedet_cache"
#data_root_dir: "/home/ming.zhang04/data/VOCdevkit/onedet_cache"

train:
    dataset: "train"
    stdout: True
    gpus: "0"
    nworkers: 4
    pin_mem: True

    momentum: 0.9
    decay: 0.0005

    clear: False

    warmup_lr: 0.0001
    lr_steps: [400,700,900,1000, 40000,60000] 
    lr_rates: [0.0005,0.001,0.002,0.02, 0.002,0.0002] 
    #lr_rates: [0.00005,0.0001,0.0002,0.002, 0.0002, 0.00002] 
    max_batches: 180200
    resize_interval: 10

    backup_interval: 200
    backup_steps: [1000]
    backup_rates: [10000]

    input_shape: [608, 608]
    batch_size: 32
    mini_batch_size: 32

    weights: ~
    #weights: "outputs/TinyYolov3/baseline/weights/backup.pt"

test:
    dataset: "test"
    stdout: True
    gpus: "0"
    #gpus: ~
    nworkers: 4
    pin_mem: True

    input_shape: [416, 416]
    batch_size: 1
#    weights: "outputs/TinyYolov3/baseline/weights/weights_60000.pt"
    weights: "outputs/TinyYolov3/baseline/weights/backup.pt"
    conf_thresh: 0.3
    nms_thresh: 0.45

    results: "results"

speed:
    gpus: "0"
    batch_size: 1
    max_iters: 200
    input_shape: [544, 544]
