output_root: "outputs"
output_version: "baseline"
backup_name: "weights"
log_name: "logs"

labels: ["aeroplane", "bicycle", "bird", "boat", "bottle", "bus", "car", "cat", "chair", "cow", "diningtable", "dog", "horse", "motorbike", "person", "pottedplant", "sheep", "sofa", "train", "tvmonitor"]

data_root_dir: "/media/lishundong/DATA2/docker/data/VOCdevkit/onedet_cache"

train:
    dataset: "train"
    stdout: True
    gpus: "0"
    nworkers: 4
    pin_mem: True

    momentum: 0.9
    decay: 0.0005

    clear: False

    warmup_lr: 0.00005
    lr_steps: [400,700,900,1000, 40000,45000]
    lr_rates: [0.0001,0.0002,0.0005,0.001, 0.0001,0.00001]
    max_batches: 80200
    resize_interval: 10

    backup_interval: 200
    backup_steps: [1000]
    backup_rates: [10000]

    input_shape: [608, 608]
    batch_size: 8
    mini_batch_size: 4
    weights: "/home/lishundong/ObjectDetection-OneStageDet/yolo/weights/darknet53.conv.74"

test:
    dataset: "test"
    stdout: True
    gpus: "0"
    nworkers: 4
    pin_mem: True

    input_shape: [544, 544]
    batch_size: 1
    weights: "outputs/Yolov3/baseline/weights/weights_50000.pt"

    conf_thresh: 0.4
    nms_thresh: 0.45

    results: "results"

speed:
    gpus: "1"
    batch_size: 1
    max_iters: 200
    input_shape: [544, 544]
